name: CI-CD pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "options to deploy in env"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - QA
          - prod

      artifact_tag:
        description: "tag to deploy"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.build_01.outputs.version }}

    steps:
      - name: Build step
        id: build_01
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test step
        run: echo "testing the build ${{ needs.build.outputs.version }}"

  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest

    steps:
      - name: Deploying the code
        run: |
          echo "Deploying version ${{ needs.build.outputs.version }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Artifact Tag: ${{ inputs.artifact_tag }}"
          echo "deploying..............!!!!"
