name: event based trigger demo
on:
  push:
   branches:
     - main
     - develop
  pull_request:
     branches:
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: |
          echo "A demo build step for event based trigger"
          echo "github variable ${{ vars.MY_NAME }}"
          echo "github secrets ${{ secrets.DOCKER_PASSWORD }}
