name: hello world
on: workflow_dispatch #need manual triiger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "A demo build"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test step
        run: echo "A demo test"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy step
        run: |
          echo " A dempo Deploy on prod1"
          echo " A demo deploy on prod2"
